run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - gocyclo
    - gosec
    - goimports
    - misspell
    - unconvert
    - predeclared
    - ineffassign
    - unused
    - gocritic
    - noctx

linters-settings:
  govet:
    enable:
      - nilness
      - shadow
  errcheck:
    check-type-assertions: true
    check-blank: false
  revive:
    rules:
      - name: exported
      - name: var-naming
      - name: receiver-naming
      - name: dot-imports
      - name: blank-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: indent-error-flow
  gocyclo:
    min-complexity: 20
  goimports:
    local-prefixes: github.com/kiviuk/moria
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - gocyclo
        - revive
    - path: _test\.go
      text: "unused-parameter"
    - path: cmd/moria/main\.go
      linters:
        - noctx
    - path: cmd/moria/messages\.go
      linters:
        - revive
      text: "error-strings|error-naming"
    - path: cmd/moria/
      linters:
        - gocritic
      text: "singleCaseSwitch"
    - path: cmd/moria/main\.go
      linters:
        - gocritic
      text: "exitAfterDefer"
